### PR TITLE
Update On/offboarding to remove mention of team.yml

### PR DESCRIPTION
**Pull request by ctro**
Remove `team.yml` guidance

### CODE REVIEW

**Review by aduth — APPROVED** [review]
Is the plan to remove this file? And if so, should we also plan to remove [the "Team Members" handbook article](https://handbook.login.gov/articles/team.html)?

**Comment by ctro** [comment]
> Is the plan to remove this file? And if so, should we also plan to remove [the "Team Members" handbook article](https://handbook.login.gov/articles/team.html)?

@aduth `team.yml` is out of date, and we can consider it deprecated.  I'm not sure if we should remove from it's own repo -- there seems to be a lot of other cruft in that repo.  Also yes we should remove the "team" page from the handbook that reads `team.yml`.  Do I need to remove anything other than the article?  Seems like maybe there is some JS someplace.

**Comment by aduth** [comment]
Yeah I think removing these two files should cover it:

- `_articles/team.md`
- `assets/js/team.tsx`

**Comment by ctro** [comment]
Yeah, sad to delete all that beautiful code :(

**Pull request merged**
