### PR TITLE
Update platform-gitlab.md

### PR DESCRIPTION
**Pull request by nick-soutouras**
Remove reference to Face/Touch Unlock

### CODE REVIEW

**Comment by aduth** [comment]
Can you share some context for this change? My understanding is that the text is accurate as-is.

**Review by timothy-spencer — APPROVED** [review]
yay!

**Comment by nick-soutouras** [comment]
@aduth To my knowledge, Biometric is not currently an approved method for accessing Gitlab.  Unless something has changed in the last couple of weeks it is just PIV or Yubikey.

**Comment by aduth** [comment]
Okay, I stumbled my way through some relevant Slack discussions and found this to be related to some compliance requirements. I think we could probably do a better job of describing the preceding sentence "You must use" to describe the actual requirements since Face/Touch is a valid phishing-resistant method, but not a blocker 🤷

**Pull request merged**
